name: Check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - run: nix flake check --accept-flake-config -L
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: check
    strategy:
      fail-fast: false
      matrix:
        target:
          - packages.x86_64-linux.iso-server
          - packages.x86_64-linux.iso-eleuthia
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - run: nix build --accept-flake-config -L ".#${{ matrix.target }}"
